using System.Collections.Generic;

namespace RESTService
{
    public class ErrorResponse
    {
        public int Code { get; set; }
        public string Type { get; set; }
        public string Message { get; set; }
        public string Description { get; set; }
        public List<string> Validations { get; set; }

        /// <summary>
        /// The relationship id generated by the service. This id is generated
        /// with the first request and used internally by the service to track
        /// any problems or for further analysis.
        /// </summary>
        /// <value>The correlation identifier.</value>
        public string CorrelationId { get; set; }
    }
}